# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "About Me - Logan Peters"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description "Your Name's academic portfolio"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://academicpages.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Logan-Peters/Logan-Peters.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Logan Peters"
  pronouns         : # example: "he/him"  
  bio              : "PhD Candidate at UC Davis"
  location         : "Davis, CA"
  employer         : "UC Davis"
  uri              : # URL
  email            : "lmtpeters@ucdavis.edu" 

  # Academic websites

  github         : https://github.com/Logan-Peters
  linkedin         : https://www.linkedin.com/in/logan-peters-054b11143/
  
# Publication Category - The following the list of publication categories and their headings
publication_category:
  manuscripts:
    title: 'Journal Articles'
    
    Peters, Logan, et al. “Peak Delta Frequency Regulates the Timing of Decisions.” Asilomar Conference on Signals, Systems, and Computers. Accepted
    
    Peters, Logan, et al. "Neural dynamics encoding risky choices during deliberation reveal separate choice subspaces. " Progress in Neurobiology 250 (2025): 102776.
    
    Overton, Jacqueline A., Karen A. Moxon, Matthew P. Stickle, Logan Peters, Jack J. Lin, Edward F. Chang, Robert T. Knight, Ming Hsu, and Ignacio Saez. "Distributed intracranial activity underlying human decision-making behavior. " Journal of Neuroscience 45.15 (2025).
    
    Zhou, Angela, Logan Peters, Karen Moxon. “Decoding Risky Decision-Making from Nonlinear Neural Latent Dynamics. ” Asilomar Conference on Signals, Systems, and Computers. Accepted
    
    Moghbel, Arianna, Logan Peters, Ignacio Saez, Karen Moxon. “Integrating choice selection and feedback during decision-making: a role for functional connectivity.” Asilomar Conference onSignals, Systems, and Computers. Accepted
    
    Moxon, Karen, Ariana Moghbel, Zhaodan Kong, Alec Roadarmel, Vincent Tran, Jochen Ditterich, Logan Peters. ”Latent variables, temporal convolutional neural networks and decision making, creating insight into how we deliberate” Asilomar Conference on Signals, Systems, and Computers. Accepted
    
    Peters, Logan M., Tarun Devesetti, Xin Liu, Ignacio Saez, Karen Moxon. “Delta regulates gamma dynamics encoding risky decision-making behavior. ” Nature Communications. In submission
    
    Moghbel, Arianna. Logan Peters, Rocelle Evangelista, Gene Gurkoff, David Brandman, Azam Alizadeh, Sheela Toprani, Karen Moxon. “Dynamics of brain-wide connectivity define a seizure-risk landscape” Brain. In submission
  
  conferences:
    title: 'Conference Presentations'
      
      Asilomar Conference on Signals, Systems, and Computers, Asilomar, CA, October 2025. Peak Delta Frequency Regulates the Timing of Decisions
      
      Society for Neuroscience Nanosymposium, San Diego, CA, November 2024. Graph Neural Networks for Reward Prediction Error
      
      Society for Neuroscience Nanosymposium, San Diego, CA, November 2023. Decoding Deliberation During Decision Making
      
      Neuroengineering Symposium, Davis, CA, May 2022, Predicting Choice from iEEG Data

# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/ for social media previews
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # change to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Social media default site image
og_description           :  # Social media default site image description
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
